# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "./crates/connect",
    "./crates/generate",
    "./crates/migrate",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Axiston License 1.0"
publish = false

authors = ["Axiston <contact@axiston.com>"]
repository = "https://github.com/axiston/database"
homepage = "https://github.com/axiston/database"
documentation = "https://github.com/axiston/database"

[workspace.dependencies]
clap = { version = "4.5", features = [] }
futures = { version = "0.3", features = [] }
tracing = { version = "0.1", features = [] }

sea-orm = { version = "1.1", features = [] }
sea-orm-migration = { version = "1.1", features = [] }
sea-orm-cli = { version = "1.1", features = [] }

thiserror = { version = "2.0", features = [] }
derive_more = { version = "1.0", features = [] }
serde = { version = "1.0", features = [] }
serde_with = { version = "3.11", features = [] }
serde_json = { version = "1.0", features = [] }

axiston-database-connect = { path = "./crates/connect", version = "0.1.0" }
axiston-database-generate = { path = "./crates/generate", version = "0.1.0" }
axiston-database-migrate = { path = "./crates/migrate", version = "0.1.0" }
