# https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "./crates/cli",
    "./crates/connect",
    "./crates/migrate",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Axiston License 1.0"
publish = false

authors = ["Axiston <contact@axiston.com>"]
repository = "https://github.com/axiston/axiston"
homepage = "https://github.com/axiston/axiston"
documentation = "https://docs.rs/axiston"

[workspace.dependencies]
axiston-database-connect = { path = "./crates/connect", version = "0.1.0" }
axiston-database-migrate = { path = "./crates/migrate", version = "0.1.0" }

sea-orm = { version = "1.1", features = ["runtime-tokio-rustls", "sqlx-postgres", "macros"] }
sea-orm-migration = { version = "1.1", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
sea-orm-cli = { version = "1.1", features = ["runtime-tokio-rustls"] }

tokio = { version = "1.41", features = ["rt-multi-thread", "macros", "process"] }
futures = { version = "0.3", features = [] }
async-trait = { version = "0.1.83", features = [] }
tracing = { version = "0.1", features = [] }

thiserror = { version = "2.0", features = [] }
anyhow = { version = "1.0", features = ["backtrace"] }

derive_more = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.11", features = [] }
