# https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "./crates/connect/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]

[migrations_directory]
dir = "./migrations"
