name: Migrate and Generate
description: Sets up PostgreSQL, runs migrations, and generates code.
runs:
    using: composite
    steps:
        -   name: Set up PostgreSQL service
            run: |
                echo "Starting PostgreSQL..."
                docker run -d --name postgres \
                  -e POSTGRES_USER=usr \
                  -e POSTGRES_PASSWORD=pwd \
                  -e POSTGRES_DB=db \
                  -p 5432:5432 postgres:latest

        -   name: Wait for PostgreSQL to be ready
            shell: bash
            run: |
                echo "Waiting for PostgreSQL..."
                for i in {1..30}; do
                  if pg_isready -h 127.0.0.1 -p 5432 -U usr; then
                    echo "PostgreSQL is ready";
                    break;
                  fi;
                  sleep 1;
                done
                if [ $i -eq 30 ]; then
                  echo "PostgreSQL did not become ready in time." >&2
                  exit 1;
                fi

        -   name: Run make:install
            run: make install

        -   name: Run make:migrate
            run: make migrate

        -   name: Run make:generate
            run: make generate

        -   name: Clean up PostgreSQL
            run: docker stop postgres && docker rm postgres
